### ISSUE TITLE
Menus?

### ISSUE THREAD

**Issue by ghost** [wbond/sublime_tortoise#1]
Using the latest Sublime Text 2 build (2051) on Win XP - I don't see any context menu entries. Any ideas? Keyboard shortcuts work fine

**Comment by wbond** [comment]
Can you open the console and see if there are any error messages when you right-click?

**Comment by ghost** [comment]
No error messages

**Comment by ghost** [comment]
My mistake - errors when right clicking on the editing window of a file under SVN control:

Traceback (most recent call last):
  File ".\sublime_plugin.py", line 189, in is_enabled_
  File ".\Tortoise.py", line 57, in handler
  File ".\Tortoise.py", line 169, in is_enabled
  File ".\Tortoise.py", line 431, in get_status
KeyError: 'status'
Traceback (most recent call last):
  File ".\sublime_plugin.py", line 187, in is_enabled_
  File ".\Tortoise.py", line 57, in handler
  File ".\Tortoise.py", line 169, in is_enabled
  File ".\Tortoise.py", line 431, in get_status
KeyError: 'status'
Traceback (most recent call last):
  File ".\sublime_plugin.py", line 199, in is_visible_
  File ".\Tortoise.py", line 57, in handler
  File ".\Tortoise.py", line 163, in is_visible
  File ".\Tortoise.py", line 431, in get_status
KeyError: 'status'
Traceback (most recent call last):
  File ".\sublime_plugin.py", line 187, in is_enabled_
  File ".\Tortoise.py", line 57, in handler
  File ".\Tortoise.py", line 190, in is_enabled
  File ".\Tortoise.py", line 431, in get_status
KeyError: 'status'
Traceback (most recent call last):
  File ".\sublime_plugin.py", line 187, in is_enabled_
  File ".\Tortoise.py", line 57, in handler
  File ".\Tortoise.py", line 190, in is_enabled
  File ".\Tortoise.py", line 431, in get_status
KeyError: 'status'
Traceback (most recent call last):
  File ".\sublime_plugin.py", line 199, in is_visible_
  File ".\Tortoise.py", line 57, in handler
  File ".\Tortoise.py", line 181, in is_visible
  File ".\Tortoise.py", line 431, in get_status
KeyError: 'status'
Traceback (most recent call last):
  File ".\sublime_plugin.py", line 199, in is_visible_
  File ".\Tortoise.py", line 57, in handler
  File ".\Tortoise.py", line 228, in is_visible
  File ".\Tortoise.py", line 431, in get_status
KeyError: 'status'
Traceback (most recent call last):
  File ".\sublime_plugin.py", line 187, in is_enabled_
  File ".\Tortoise.py", line 57, in handler
  File ".\Tortoise.py", line 292, in is_enabled
  File ".\Tortoise.py", line 431, in get_status
KeyError: 'status'
Traceback (most recent call last):
  File ".\sublime_plugin.py", line 187, in is_enabled_
  File ".\Tortoise.py", line 57, in handler
  File ".\Tortoise.py", line 292, in is_enabled
  File ".\Tortoise.py", line 431, in get_status
KeyError: 'status'
Traceback (most recent call last):
  File ".\sublime_plugin.py", line 199, in is_visible_
  File ".\Tortoise.py", line 57, in handler
  File ".\Tortoise.py", line 287, in is_visible
  File ".\Tortoise.py", line 431, in get_status
KeyError: 'status'
Traceback (most recent call last):
  File ".\sublime_plugin.py", line 187, in is_enabled_
  File ".\Tortoise.py", line 57, in handler
  File ".\Tortoise.py", line 257, in is_enabled
  File ".\Tortoise.py", line 431, in get_status
KeyError: 'status'
Traceback (most recent call last):
  File ".\sublime_plugin.py", line 187, in is_enabled_
  File ".\Tortoise.py", line 57, in handler
  File ".\Tortoise.py", line 257, in is_enabled
  File ".\Tortoise.py", line 431, in get_status
KeyError: 'status'
Traceback (most recent call last):
  File ".\sublime_plugin.py", line 199, in is_visible_
  File ".\Tortoise.py", line 57, in handler
  File ".\Tortoise.py", line 252, in is_visible
  File ".\Tortoise.py", line 431, in get_status
KeyError: 'status'

Errors when right clicking on a file in the folder tree:

Traceback (most recent call last):
  File ".\sublime_plugin.py", line 185, in is_enabled_
  File ".\Tortoise.py", line 57, in handler
  File ".\Tortoise.py", line 150, in is_enabled
  File ".\Tortoise.py", line 431, in get_status
KeyError: 'status'
Traceback (most recent call last):
  File ".\sublime_plugin.py", line 197, in is_visible_
  File ".\Tortoise.py", line 57, in handler
  File ".\Tortoise.py", line 145, in is_visible
  File ".\Tortoise.py", line 431, in get_status
KeyError: 'status'
Traceback (most recent call last):
  File ".\sublime_plugin.py", line 185, in is_enabled_
  File ".\Tortoise.py", line 57, in handler
  File ".\Tortoise.py", line 216, in is_enabled
  File ".\Tortoise.py", line 431, in get_status
KeyError: 'status'
Traceback (most recent call last):
  File ".\sublime_plugin.py", line 185, in is_enabled_
  File ".\Tortoise.py", line 57, in handler
  File ".\Tortoise.py", line 216, in is_enabled
  File ".\Tortoise.py", line 431, in get_status
KeyError: 'status'
Traceback (most recent call last):
  File ".\sublime_plugin.py", line 197, in is_visible_
  File ".\Tortoise.py", line 57, in handler
  File ".\Tortoise.py", line 202, in is_visible
  File ".\Tortoise.py", line 431, in get_status
KeyError: 'status'
Traceback (most recent call last):
  File ".\sublime_plugin.py", line 197, in is_visible_
  File ".\Tortoise.py", line 57, in handler
  File ".\Tortoise.py", line 240, in is_visible
  File ".\Tortoise.py", line 431, in get_status
KeyError: 'status'
Traceback (most recent call last):
  File ".\sublime_plugin.py", line 185, in is_enabled_
  File ".\Tortoise.py", line 57, in handler
  File ".\Tortoise.py", line 309, in is_enabled
  File ".\Tortoise.py", line 431, in get_status
KeyError: 'status'
Traceback (most recent call last):
  File ".\sublime_plugin.py", line 185, in is_enabled_
  File ".\Tortoise.py", line 57, in handler
  File ".\Tortoise.py", line 309, in is_enabled
  File ".\Tortoise.py", line 431, in get_status
KeyError: 'status'
Traceback (most recent call last):
  File ".\sublime_plugin.py", line 197, in is_visible_
  File ".\Tortoise.py", line 57, in handler
  File ".\Tortoise.py", line 304, in is_visible
  File ".\Tortoise.py", line 431, in get_status
KeyError: 'status'
Traceback (most recent call last):
  File ".\sublime_plugin.py", line 185, in is_enabled_
  File ".\Tortoise.py", line 57, in handler
  File ".\Tortoise.py", line 274, in is_enabled
  File ".\Tortoise.py", line 431, in get_status
KeyError: 'status'
Traceback (most recent call last):
  File ".\sublime_plugin.py", line 185, in is_enabled_
  File ".\Tortoise.py", line 57, in handler
  File ".\Tortoise.py", line 274, in is_enabled
  File ".\Tortoise.py", line 431, in get_status
KeyError: 'status'
Traceback (most recent call last):
  File ".\sublime_plugin.py", line 197, in is_visible_
  File ".\Tortoise.py", line 57, in handler
  File ".\Tortoise.py", line 269, in is_visible
  File ".\Tortoise.py", line 431, in get_status
KeyError: 'status'

**Comment by wbond** [comment]
This is fixed in the latest version
