### ISSUE TITLE
No right-click menus? error: [Error 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by avggeek** [wbond/sublime_tortoise#15]
Hi, 

I get the following error message whenever I right-click on a file that has been committed to Git - "error: [Error 2] The system cannot find the file specified"

I have added the parent folder that contains the hidden ".git" folder and modified Tortoise.sublime-settings - User to specify location of TortoiseProc.exe but this does not seem to help.

Error log from console is:

error: [Error 2] The system cannot find the file specified
Traceback (most recent call last):
  File ".\sublime_plugin.py", line 268, in is_enabled_
  File ".\Tortoise.py", line 71, in handler
  File ".\Tortoise.py", line 160, in is_enabled
  File ".\Tortoise.py", line 446, in get_status
  File ".\Tortoise.py", line 353, in process_status
UnboundLocalError: local variable 'status' referenced before assignment
error: [Error 2] The system cannot find the file specified
Traceback (most recent call last):
  File ".\sublime_plugin.py", line 268, in is_enabled_
  File ".\Tortoise.py", line 71, in handler
  File ".\Tortoise.py", line 160, in is_enabled
  File ".\Tortoise.py", line 446, in get_status
  File ".\Tortoise.py", line 353, in process_status
UnboundLocalError: local variable 'status' referenced before assignment
error: [Error 2] The system cannot find the file specified
Traceback (most recent call last):
  File ".\sublime_plugin.py", line 280, in is_visible_
  File ".\Tortoise.py", line 71, in handler
  File ".\Tortoise.py", line 152, in is_visible
  File ".\Tortoise.py", line 446, in get_status
  File ".\Tortoise.py", line 353, in process_status
UnboundLocalError: local variable 'status' referenced before assignment
error: [Error 2] The system cannot find the file specified
Traceback (most recent call last):
  File ".\sublime_plugin.py", line 268, in is_enabled_
  File ".\Tortoise.py", line 71, in handler
  File ".\Tortoise.py", line 185, in is_enabled
  File ".\Tortoise.py", line 446, in get_status
  File ".\Tortoise.py", line 353, in process_status
UnboundLocalError: local variable 'status' referenced before assignment
error: [Error 2] The system cannot find the file specified
Traceback (most recent call last):
  File ".\sublime_plugin.py", line 268, in is_enabled_
  File ".\Tortoise.py", line 71, in handler
  File ".\Tortoise.py", line 185, in is_enabled
  File ".\Tortoise.py", line 446, in get_status
  File ".\Tortoise.py", line 353, in process_status
UnboundLocalError: local variable 'status' referenced before assignment
error: [Error 2] The system cannot find the file specified
Traceback (most recent call last):
  File ".\sublime_plugin.py", line 280, in is_visible_
  File ".\Tortoise.py", line 71, in handler
  File ".\Tortoise.py", line 177, in is_visible
  File ".\Tortoise.py", line 446, in get_status
  File ".\Tortoise.py", line 353, in process_status
UnboundLocalError: local variable 'status' referenced before assignment
error: [Error 2] The system cannot find the file specified
Traceback (most recent call last):
  File ".\sublime_plugin.py", line 268, in is_enabled_
  File ".\Tortoise.py", line 71, in handler
  File ".\Tortoise.py", line 214, in is_enabled
  File ".\Tortoise.py", line 446, in get_status
  File ".\Tortoise.py", line 353, in process_status
UnboundLocalError: local variable 'status' referenced before assignment
error: [Error 2] The system cannot find the file specified
Traceback (most recent call last):
  File ".\sublime_plugin.py", line 268, in is_enabled_
  File ".\Tortoise.py", line 71, in handler
  File ".\Tortoise.py", line 214, in is_enabled
  File ".\Tortoise.py", line 446, in get_status
  File ".\Tortoise.py", line 353, in process_status
UnboundLocalError: local variable 'status' referenced before assignment
error: [Error 2] The system cannot find the file specified
Traceback (most recent call last):
  File ".\sublime_plugin.py", line 280, in is_visible_
  File ".\Tortoise.py", line 71, in handler
  File ".\Tortoise.py", line 202, in is_visible
  File ".\Tortoise.py", line 446, in get_status
  File ".\Tortoise.py", line 353, in process_status
UnboundLocalError: local variable 'status' referenced before assignment
error: [Error 2] The system cannot find the file specified
Traceback (most recent call last):
  File ".\sublime_plugin.py", line 280, in is_visible_
  File ".\Tortoise.py", line 71, in handler
  File ".\Tortoise.py", line 228, in is_visible
  File ".\Tortoise.py", line 446, in get_status
  File ".\Tortoise.py", line 353, in process_status
UnboundLocalError: local variable 'status' referenced before assignment
error: [Error 2] The system cannot find the file specified
Traceback (most recent call last):
  File ".\sublime_plugin.py", line 268, in is_enabled_
  File ".\Tortoise.py", line 71, in handler
  File ".\Tortoise.py", line 272, in is_enabled
  File ".\Tortoise.py", line 446, in get_status
  File ".\Tortoise.py", line 353, in process_status
UnboundLocalError: local variable 'status' referenced before assignment
error: [Error 2] The system cannot find the file specified
Traceback (most recent call last):
  File ".\sublime_plugin.py", line 268, in is_enabled_
  File ".\Tortoise.py", line 71, in handler
  File ".\Tortoise.py", line 272, in is_enabled
  File ".\Tortoise.py", line 446, in get_status
  File ".\Tortoise.py", line 353, in process_status
UnboundLocalError: local variable 'status' referenced before assignment
error: [Error 2] The system cannot find the file specified
Traceback (most recent call last):
  File ".\sublime_plugin.py", line 280, in is_visible_
  File ".\Tortoise.py", line 71, in handler
  File ".\Tortoise.py", line 264, in is_visible
  File ".\Tortoise.py", line 446, in get_status
  File ".\Tortoise.py", line 353, in process_status
UnboundLocalError: local variable 'status' referenced before assignment
error: [Error 2] The system cannot find the file specified
Traceback (most recent call last):
  File ".\sublime_plugin.py", line 268, in is_enabled_
  File ".\Tortoise.py", line 71, in handler
  File ".\Tortoise.py", line 250, in is_enabled
  File ".\Tortoise.py", line 446, in get_status
  File ".\Tortoise.py", line 353, in process_status
UnboundLocalError: local variable 'status' referenced before assignment
error: [Error 2] The system cannot find the file specified
Traceback (most recent call last):
  File ".\sublime_plugin.py", line 268, in is_enabled_
  File ".\Tortoise.py", line 71, in handler
  File ".\Tortoise.py", line 250, in is_enabled
  File ".\Tortoise.py", line 446, in get_status
  File ".\Tortoise.py", line 353, in process_status
UnboundLocalError: local variable 'status' referenced before assignment
error: [Error 2] The system cannot find the file specified
Traceback (most recent call last):
  File ".\sublime_plugin.py", line 280, in is_visible_
  File ".\Tortoise.py", line 71, in handler
  File ".\Tortoise.py", line 242, in is_visible
  File ".\Tortoise.py", line 446, in get_status
  File ".\Tortoise.py", line 353, in process_status
UnboundLocalError: local variable 'status' referenced before assignment

I am running Sublime Text 2 Build 1281/TortoiseGit 1.7.9.0 with msysgit 1.7.10 on Windows7/64-bit

**Comment by schlamar** [comment]
Duplicate of #10, fix is in #11

**Comment by avggeek** [comment]
Confirmed that patch in #11 resolves the issue.

**Comment by IbnSaeed** [comment]
It is still not fixed in the latest release. 

How was this bug closed ?

**Comment by KevinSheedy** [comment]
This is still not working. Can we re-open this bug?
It works for SVN but not for Git even though the paths to the .exe files are very similar.

Tortoise Version 2013.01.16.00.37.23
Sublime Version 2.0.1, Build 2217

**Comment by wbond** [comment]
Yeah, we can re-open it, however unfortunately I don't have time for care and feeding of this package any longer.

If there is someone interested in running with it, the new channel infrastructure with PC 2.0 that is coming out soon should make the transition of this pretty easy.

**Comment by atwright147** [comment]
Hi guys,

With the newest TortoiseGit on Win7 you seem to need to change your config to contain the following:

```
{
    "git_tgit_path": "C:\\Program Files (x86)\\Git\\bin\\git.exe",
    "git_tortoiseproc_path": "C:\\Program Files\\TortoiseGit\\bin\\TortoiseGitProc.exe"
}
```

You will also need to use the repo I have been maintaining: https://github.com/atwright147/sublime_tortoise

I have gathered all of the fixes from the open issues and merged them but I'm not a Python dev so Icannot properly maintain this plugin.

**Comment by johnlouie04** [comment]
it is still not fixed I also having this issue [error 2]

**Comment by atwright147** [comment]
@johnlouie04 have you tried my fork? You will have to clone it into your packages folder -- it isn't in Package Control

**Comment by gasatrya** [comment]
@atwright147 thanks a lot, it works perfecly :)
