### ISSUE TITLE
Context menu on files

### ISSUE THREAD

**Issue by williamledoux** [wbond/sublime_tortoise#6]
Hi again,

Not sure that this is a bug, but there is no tortoise context menu when right clicking on a specific file that is inside a versionned project.
It would be nice to have options such as Diff and Log (file history), or maybe even Annotate/Blame.

Thanks for your work !
William

**Comment by wbond** [comment]
Does it work for any of the files in the repository? Are there any errors in the console?

**Comment by williamledoux** [comment]
It does not work on any file of the project (even in not-nested repositories).
I forgot to look for errors, but yes, there is a bunch of. They're all the same though

```
  IndentationError: unexpected indent
  Traceback (most recent call last):
    File ".\sublime_plugin.py", line 200, in is_enabled_
    File ".\Tortoise.py", line 75, in handler
    File ".\Tortoise.py", line 164, in is_enabled
    File ".\Tortoise.py", line 516, in get_status
  AttributeError: TortoiseHg instance has no attribute 'process_status'
  Traceback (most recent call last):
    File ".\sublime_plugin.py", line 200, in is_enabled_
    File ".\Tortoise.py", line 75, in handler
    File ".\Tortoise.py", line 164, in is_enabled
    File ".\Tortoise.py", line 516, in get_status
  AttributeError: TortoiseHg instance has no attribute 'process_status'
  Traceback (most recent call last):
    File ".\sublime_plugin.py", line 212, in is_visible_
    File ".\Tortoise.py", line 75, in handler
    File ".\Tortoise.py", line 156, in is_visible
    File ".\Tortoise.py", line 516, in get_status
  AttributeError: TortoiseHg instance has no attribute 'process_status'
  Traceback (most recent call last):
    File ".\sublime_plugin.py", line 200, in is_enabled_
    File ".\Tortoise.py", line 75, in handler
    File ".\Tortoise.py", line 192, in is_enabled
    File ".\Tortoise.py", line 516, in get_status
  AttributeError: TortoiseHg instance has no attribute 'process_status'
  Traceback (most recent call last):
    File ".\sublime_plugin.py", line 200, in is_enabled_
    File ".\Tortoise.py", line 75, in handler
    File ".\Tortoise.py", line 192, in is_enabled
    File ".\Tortoise.py", line 516, in get_status
  AttributeError: TortoiseHg instance has no attribute 'process_status'
  Traceback (most recent call last):
    File ".\sublime_plugin.py", line 212, in is_visible_
    File ".\Tortoise.py", line 75, in handler
    File ".\Tortoise.py", line 182, in is_visible
    File ".\Tortoise.py", line 516, in get_status
  AttributeError: TortoiseHg instance has no attribute 'process_status'
  Traceback (most recent call last):
  File ".\sublime_plugin.py", line 212, in is_visible_
  File ".\Tortoise.py", line 75, in handler
  File ".\Tortoise.py", line 208, in is_visible
  File ".\Tortoise.py", line 516, in get_status
AttributeError: TortoiseHg instance has no attribute 'process_status'
Traceback (most recent call last):
  File ".\sublime_plugin.py", line 200, in is_enabled_
  File ".\Tortoise.py", line 75, in handler
  File ".\Tortoise.py", line 252, in is_enabled
  File ".\Tortoise.py", line 516, in get_status
AttributeError: TortoiseHg instance has no attribute 'process_status'
Traceback (most recent call last):
  File ".\sublime_plugin.py", line 200, in is_enabled_
  File ".\Tortoise.py", line 75, in handler
  File ".\Tortoise.py", line 252, in is_enabled
  File ".\Tortoise.py", line 516, in get_status
AttributeError: TortoiseHg instance has no attribute 'process_status'
Traceback (most recent call last):
  File ".\sublime_plugin.py", line 212, in is_visible_
  File ".\Tortoise.py", line 75, in handler
  File ".\Tortoise.py", line 244, in is_visible
  File ".\Tortoise.py", line 516, in get_status
AttributeError: TortoiseHg instance has no attribute 'process_status'
Traceback (most recent call last):
  File ".\sublime_plugin.py", line 200, in is_enabled_
  File ".\Tortoise.py", line 75, in handler
  File ".\Tortoise.py", line 230, in is_enabled
  File ".\Tortoise.py", line 516, in get_status
AttributeError: TortoiseHg instance has no attribute 'process_status'
Traceback (most recent call last):
  File ".\sublime_plugin.py", line 200, in is_enabled_
  File ".\Tortoise.py", line 75, in handler
  File ".\Tortoise.py", line 230, in is_enabled
  File ".\Tortoise.py", line 516, in get_status
AttributeError: TortoiseHg instance has no attribute 'process_status'
Traceback (most recent call last):
  File ".\sublime_plugin.py", line 212, in is_visible_
  File ".\Tortoise.py", line 75, in handler
  File ".\Tortoise.py", line 222, in is_visible
  File ".\Tortoise.py", line 516, in get_status
AttributeError: TortoiseHg instance has no attribute 'process_status'
```

**Comment by wbond** [comment]
This should be fixed in version 1.1.4 (17b390d7). The new version also includes significantly better handling of file paths with spaces when using TortoiseHg.

**Comment by williamledoux** [comment]
Works perfectly, Thanks !
Do you plan to add a Blame/Annotate context menu item ?

**Comment by wbond** [comment]
That is a good idea, I'll open a new ticket for that.

**Comment by wbond** [comment]
I just added the blame context menu and keyboard shortcut in the latest version
